### PR TITLE
Miscellaneous flags for HTTP module and HTTP POST body support (chunked and plain)

### PR DESCRIPTION
**Pull request by mzpqnxow**
As described in #338 (and the title of the PR)

Needs review, though it is currently working well enough for me. I'm not a golang guy

### CODE REVIEW

**Comment by mzpqnxow** [comment]
@dadrian @zakird any interest in accepting this one, or any feedback on how it was implemented?

Looks like there are some merge conflicts since I sent it, I can fix them up if you have interest in merging

Thanks!

**Comment by mzpqnxow** [comment]
@dadrian @zakird bump... thoughts? It's all optional, requiring explicit flags to the `http` module CLI, so I'm thinking this would have a small (ideally zero) impact on users. It's worked well for me to date

**Comment by dadrian** [comment]
This seems fine but please fix the merge and then @ me again

**Comment by mzpqnxow** [comment]
Yeah, I'm a doofus and based this on TLS1.3, but submitted against master. D'oh!

I only use TLS1.3 so selfishly I would like to resubmit against TLS1.3 only, but I'll see if I can adapt it to master, it shouldn't be too bad, I guess

**Comment by lc** [comment]
Hey @dadrian @mzpqnxow – this would be really awesome to have!

**Comment by mzpqnxow** [comment]
> Hey @dadrian @mzpqnxow – this would be really awesome to have!

Been meaning to get back around to rebasing this

You wouldn't happen to write/work with golang code would you? My commits are all here, they just needs to be grafted onto the correct branch

I want to do it but haven't had the time, and I have a build of that branch handy whenever I need it, which has let me keep deferring this

**Comment by mzpqnxow** [comment]
> Hey @dadrian @mzpqnxow – this would be really awesome to have!

@lc any interest in taking this over from me? It works but needs to be rebased. I haven't had any time, unfortunately

**Comment by mzpqnxow** [comment]
Oops, I see @lc already did it! Thanks!

**Pull request closed without merging**
