### PR TITLE
Implement timeout to accept float value

### PR DESCRIPTION
**Pull request by ajholland**
This PR implements changing timeout from an int value to a float so that one may use 0.5 as a timeout for example. 

## How to Test

`echo httpstat.us | zgrab2 http --timeout 3.5 --endpoint="/200?sleep=7000"`

## Notes & Caveats

I'm not sure why lines 81-86 in modules/http/scanner.go appear as different, those came from go fmt running when I saved the file. I'm guessing this is because I'm using go version 1.9. I can change that if you'd like.

Tacking on a "s" in order to use ParseDuration isn't ideal, but is in my opinion more simple than writing a custom function to parse out seconds, milliseconds, etc...

## Issue Tracking

#73

### CODE REVIEW

**Comment by justinbastress** [comment]
Since it's a string anyway, any reason we shouldn't just let the user specify the suffix, rather than unconditionally tacking on the `"s"`? If the value ends in a number we can still append the "s", but otherwise it could be nice to allow e.g "10m", "0.5s", "500us", etc.

**Comment by justinbastress** [comment]
Actually, it would be nice to have this in zflags -- i.e., specifying the input type as `time.Duration`, it does this conversion automatically.

**Comment by ajholland** [comment]
Apparently, it does this already!

**Comment by justinbastress** [comment]
I'm ambivalent as to requiring the unit suffix, but that would obviously be a zflags feature, and I see no problem with explicitly specifying it in the integration scripts here.

**Comment by zakird** [comment]
@ajholland I can't tell from the examples, right now, if you just pass in a straight integer, e.g., `10` not `10s`, will it treat that as seconds?

**Comment by zakird** [comment]
I've fixed the merge conflict, but it'd be nice to get this merged before we have to do that again. ;)

**Comment by ajholland** [comment]
screen shot 2018-06-28 at 11 02 09 pm
This is the behavior in this PR for passing in 10 vs 10s. 

I could write a function (probably in zflags) that checks if units are given, if not, assumes seconds?

**Comment by zakird** [comment]
I think that would probably be the most user-friendly option if it's not awful to implement.

**Comment by ajholland** [comment]
@zakird @justinbastress I think this can be merged now

**Pull request merged**
