### PR TITLE
Add option to flush output after each line of output

### PR DESCRIPTION
**Pull request by cablej**
This PR adds an option to flush output after each line of output. This may be desirable in streaming applications, where a program continually ingests zgrab2's output.

## How to Test

Run zgrab2 with the flag `--flush`. Observe that the output will be flushed after each line, rather than at the end.

### CODE REVIEW

**Comment by luciddr34m3r** [comment]
Will this be merged?

**Comment by SoloSteve** [comment]
I would also appreciate this feature

**Review by dadrian — APPROVED** [review]

**Comment by fbexiga** [comment]
This change broke the build, did no one test this first?

**Comment by dadrian** [comment]
> This change broke the build, did no one test this first?

This comment broke my graciousness, did no one think first?

**Comment by frbexiga** [comment]
I apologize if my previous comment violated some guidelines, I removed it since it has. As a contributor (one-time but still) and a user of these tools myself, I was trying to alert of the issue, and didn't submit a PR myself because I'm not familiar with the code enough to know if I wouldn't break it again. I didn't mean anything else by it.

That said, I think blocking me from the org was kind of a drastic measure. Would you mind unblocking me?

**Pull request merged**
