### PR TITLE
Add error handling for FTP TLS handshake

### PR DESCRIPTION
**Pull request by hmcguinn**
This pull requests adds a check in modules/ftp/scanner.go for an error upon completing a TLS handshake.

### CODE REVIEW

**Comment by zakird** [comment]
This looks like it will prevent attempting to grab banner if the TLS handshake fails. I believe that this is the right thing to do since it's a TLS wrapped FTP session not running TLS after FTP has started. @codyprime can you confirm that this makes sense?

**Review by zakird — APPROVED** [review]
LGTM unless @codyprime flags something in the logic.

**Review by codyprime — APPROVED** [review]
looks good to me as well, thanks

**Comment by codyprime** [comment]
> This looks like it will prevent attempting to grab banner if the TLS handshake fails. I believe that this is the right thing to do since it's a TLS wrapped FTP session not running TLS after FTP has started. @codyprime can you confirm that this makes sense?

Yeah, I also believe this is the correct thing to do, since in this path TLS was requested for this scan.  We should error out if we cannot establish a TLS connection.

**Pull request merged**
